eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
server:
    port: 9091
spring:
    application:
        name: eureka